# Generated by Django 3.0.6 on 2020-08-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200823_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='AUTHOR NAME', max_length=120),
        ),
    ]
