# Generated by Django 3.0.6 on 2020-08-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='static/img/snow.jpg', null=True, upload_to=''),
        ),
    ]
