# Generated by Django 3.0.6 on 2020-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20200823_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
