# Generated by Django 3.0.6 on 2020-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20200823_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=models.FileField(blank=True, default='author_default.jpg', null=True, upload_to=''),
        ),
    ]
