# Generated by Django 3.0.6 on 2020-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200823_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=models.FileField(blank=True, default='author_default.png', null=True, upload_to=''),
        ),
    ]
